Changes needed to build ppgplot on g2
Currently Loaded Modulefiles:
 1) python/2.7.2                     3) mpfr/x86_64/gnu/3.1.1            5) gcc/4.7.1
 2) gmp/x86_64/gnu/5.0.5             4) mpc/x86_64/gnu/1.0               6) pgplot/x86_64/gnu/5.2-gcc-4.7.1

 Needed to add gfortran to libraries in setup.py and location of gcc
 libraries in setup.cfg. This is to fix the following runtime error:

Python 2.7.2 (default, Jul 16 2013, 11:39:13)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ppgplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    File "/home/sjanssen/lib/python/ppgplot/__init__.py", line 1, in <module>
        from _ppgplot import *
	ImportError: /usr/local/x86_64/gnu/pgplot-5.2-gcc-4.7.1/libpgplot.so: undefined symbol: _gfortran_concat_string